#!/bin/bash
CONTAINER_NAME="express-simple-api-template"
APP_DOCKER_HOST_IP=`ifconfig | grep "inet " | grep -Fv 127.0.0.1 | grep -Fv 127.0.0.1 | awk '{print $2}' | cut -d ':' -f 2 | cut -d ' ' -f 1 | awk 'FNR == 1'`
APP_DOCKER_HOST_USER=`whoami`
[[ -n $SQL_DB_URL ]] || SQL_DB_URL="postgres://$APP_DOCKER_HOST_USER:@$APP_DOCKER_HOST_IP:5432/example_app_db"
[[ -n $APP_DOCKER_NET ]] || APP_DOCKER_NET="bridge"
[[ -n $APP_PORT ]] || APP_PORT="2000"
