#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

trap "exit" INT TERM ERR
trap "kill 0" EXIT

if [[ $* == *--help* ]]; then
  echo "runs dev environment"
  echo
  exit
fi

(cd $DIR/../vibes-discord-bot && npm start) &
(cd $DIR/../vibes-site && npm start) | cat - &

wait