name: Notify Team
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            ${{ github.actor }} on ${{ github.repository }}: ${{ github.event.commits[0].message }}
            https://github.com/${{ github.repository }}/commit/${{github.sha}}